// https://www.youtube.com/watch?v=kCAenEFSMUY

//  imaginemos una response que devuelva una Review, pero esa Review tiene datos de un User, de una Product Review y de ella misma (crecimiento horizontal y vertical del Agregado, en este caso la Review tiene un User dentro, aparte de datos de ella, luego Review ha crecido tanto vertical como horizontalmente). Esto lo hace más complicado de mantener. Aparte Review está dentro de Producto, que es el Agregado y Review no es accesible sino a través de Product
// En este punto se puede separar ese Agregado, pero tiene que ser siempre en base a que también se pueda tratar como ciudadanos de primera clase a Review y User, es decir, que podamos crear solo Reviews o Users en algun otro lado.Fijate en la imagen con los dos dominios con el agregado separado, cada uno de ellos es un bounded context
// Pasaríamos tmb de usar un GET /products/{id} donde nos traería todo ese mega agregado (Select * from products left join reviews left joint users) a que ese endpoint solo devuelva products (quitamos los joins) y hubiera que llamar tmb a GET /reviews?product_id={id} y a GET /users?=[{id1},{id2},...]
// Esto obviamente agrega una capa de complejidad y aparte parece mucho más ineficiente, ya que hay que hacer tres queries y tres consultas al back desde el front. Un agregado es un elemento conceptual, y un agregado necesita tener un aggregateRoot para serlo,fijate que puede tener varias entidades, es una simple agrupación con una ruta de entrada (product.review, product.id),etc. Una Entidad es Product o Review o User,etc
// Ojo, al hacer un new Product (siendo Product un agregado) hay que crear incluso la Review, esa agrupación es indivisible, tanto para consultarla o crearla,entiendo (luego Product está acoplado con Review)En resumen, hay un único punto de entrada. Un agregado puede ser útil por ejemplo, para aplicar reglas de negocio como 'Un producto solo puede tener 300 reviews'. Al crear ese agregado y establecer un único punto de entrada es muy fácil saber si hay más de 300 reviews
// Este agregado podría crecer horizontalmente por ejemplo agregando la Entidad Sellers (al agregado Producto) para saber qué vendedores ofrecen ese producto; o agregando la Entidad Categoría,etd. Fijate que en NttData usabamos agregados muchas veces. Si creciera mucho horizontalmente el código se hace inmantenible.Fijate que ese agregado va a tener que tener todos los métodos de las Entidades que lo componen, pues es una pieza atómica.Esto es crecimiento horizontal
// Tmb puede crecer verticalmente. Esto se da cuando las Entidades que lo componen a su vez crecen, por ejempo Review podria tener dentro un User, al hacer ese cambio está creciendo verticalmente el agregado. Realmente da igual el tipo de crecimiento, el resultado va a ser que el Agregado tiene que crecer y de nuevo se puede volver inmantenible
// Ley de Demeter (o ley de endogamía): En POO favorece la relación con lo que está dentro y no lo de fuera, pero se suele asociar con la frase 'No hables con desconocidos'. Y esto es porque, a partir de ciertas reglas sencillas, lo que busca es que un objeto solo se relacione consigo mismo todo lo posible. 
// Siempre descompon un programa grande en pequeños problemas
// Mejorar la actitud en relación a cometer errores, a no frustrarme cuando algo no lo sepa, a tener confianza en que resolveré algo muy complejo, etc
// https://www.youtube.com/watch?v=6zKbNn60TjA